# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: EMK Complexity Group
email: E.Mitleton-Kelly@lse.ac.uk
# description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://emk-complexity.org" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username:
# github_username: "EMK-Complexity"

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

timezone: Europe/London
minima:
  date_format: "%a %e %b %Y"

header_pages:
  - events.html
  - publications.md
  - projects.md
  - complexity_guide.md
  - about.md
  
excerpt_separator: <!--break-->

collections:
  events:
    output: true
    permalink: /:collection/:name.html
  posts:
    permalink: /news/:name.html
  projects:
    output: true
    permalink: /:collection/:name.html
  guide:
    output: true
    permalink: /:collection/:name.html    
      
defaults:
  - scope:
      path: _events
      type: events
    values:
      layout: event
  - scope:
      path: _projects
      type: projects
    values:
      layout: page
  - scope:
      path: _guide
      type: guide
    values:
      layout: page

path_to_audio_files: http://emk-complexity.s3.amazonaws.com/audio/ # with trailing slash
path_to_bucket: http://emk-complexity.s3.amazonaws.com # no trailing slash
